### ISSUE TITLE
Support other log formats

### ISSUE THREAD

**Issue by jfinzel** [ankane/dexter#13]
Most (at least many) users of postgres in production use csvlog format, and it appears dexter does not support this.  Also, other tools used required csv format such as pgbadger.  This means I can't feed our production logs into dexter and so effectively I can't use it (unless I reformat the log files manually).

Can this support be added for csv format (and other log_line_prefix settings)?

**Comment by ankane** [comment]
Hey @jfinzel, big thanks for all the feedback 💯 

Supporting more log formats makes sense and shouldn't be too difficult. I'll try to add this in the next week.

**Comment by ankane** [comment]
Hey @jfinzel, I added support for csv format. `log_line_prefix` isn't needed, as this is automatically stripped in the current implementation.
