### ISSUE TITLE
Dexter runs ANALYZE with no warning and no docs

### ISSUE THREAD

**Issue by jfinzel** [ankane/dexter#17]
There are reasons not to simply run `ANALYZE` automatically on massive tables, which dexter does without any note in the docs.  At the very least, there needs to be a warning in the docs that you will automatically run analyze on tables out of date by whatever amount of time.

And it's not a good idea.  It would be better to remove this code entirely, and suggest in the docs that DBAs freshly analyze their database before running dexter, or rather that they have auto-analyze tuned appropriately, before running dexter.  This is too invasive for a production system as it stands.

**Comment by ankane** [comment]
Hey @jfinzel, that's fair. I've updated the default behavior to not `ANALYZE`.
