### ISSUE TITLE
Possible error with columns with upper case characters

### ISSUE THREAD

**Issue by fvictorio** [ankane/dexter#2]
Hello, I tried dexter and I ran into this problem:

I installed and executed it, and tried to do a couple of queries in my DB. Then I got this error:

```
/var/lib/gems/2.3.0/gems/pgdexter-0.1.2/lib/dexter/indexer.rb:234:in `exec_params': ERROR:  hypopg: column "fromid" does not exist (PG::InternalError)
```

I have a `fromId` column, not a `fromid`. Is it possible that the column names are not being surrounded with double quotes? I am not sure if this is a problem with dexter, hypopg or pg_query.

Hope that helps.

**Comment by ankane** [comment]
Hey @fvictorio, thanks for reporting 👍  Fixed on master.

**Comment by fvictorio** [comment]
Thanks! Could you add a section in the Readme with instructions for building dexter? I have no idea how to build and execute a Ruby project.

**Comment by ankane** [comment]
Good idea. Added.
