### ISSUE TITLE
Installation via package does not work

### ISSUE THREAD

**Issue by alexanderadam** [ankane/dexter#26]
First of all: dexter is awesome! I like the idea and how it's done. This is wonderful! So thank you for dexter.

I tried to install dexter within [the official Postgres Docker container](https://hub.docker.com/_/postgres/) and everything went fine until I actually tried to run dexter. It resulted in an error that looks a bit [like a old bundler error](https://github.com/bundler/bundler/issues/2104):

![screenshot_20180321_152302](https://user-images.githubusercontent.com/372620/37716855-c79521d2-2d1f-11e8-91f1-2d35017599d2.png)

I "solved" it by installing it via the traditional way (current ruby + rubygems) and everything went fine. So I guess that the binary packages don't run flawlessly on every system.

**Comment by ankane** [comment]
Hey @alexanderadam, thanks for another report 👍 Which platform are you on? My guess is the package is missing a dependency for that platform.

**Comment by alexanderadam** [comment]
It's the official [Postgres 9.4 Docker container](https://github.com/docker-library/postgres/blob/61e369ce3738e38386fa01ce4809c2304e76257c/9.4/Dockerfile) (Debian Jessie).

**Comment by ankane** [comment]
Hey @alexanderadam, I'm unable to repro. Can you share the Dockerfile you're using?

**Comment by alexanderadam** [comment]
I did not create a separate Dockerfile. I just used the linked one and executed this within the container for development purposes:

```bash
apt update && apt install curl build-essentials build-essential wget apt-transport-https git postgresql-server-dev-9.4
curl -L https://dl.packager.io/srv/pghero/dexter/key | sudo apt-key add -
wget -O /etc/apt/sources.list.d/dexter.list https://dl.packager.io/srv/pghero/dexter/master/installer/debian/9.repo
wget -O /etc/apt/sources.list.d/dexter.list https://dl.packager.io/srv/pghero/dexter/master/installer/debian/8.repo
apt update && apt install dexter

cd /tmp
git clone https://github.com/HypoPG/hypopg.git
cd hypopg
make && make install
```

**Comment by ankane** [comment]
Any reason you're installing the Debian 9 package instead of just 8? The following works fine for me with the `postgres:9.4` image:

```sh
apt update && apt install curl build-essential wget apt-transport-https git postgresql-server-dev-9.4
curl -L https://dl.packager.io/srv/pghero/dexter/key | apt-key add -
wget -O /etc/apt/sources.list.d/dexter.list https://dl.packager.io/srv/pghero/dexter/master/installer/debian/8.repo
apt-get update
apt-get install dexter
```

**Comment by alexanderadam** [comment]
Oh, that was indeed by accident. My fault, sorry. 😳
