### ISSUE TITLE
Argument parsing doesn't seem to work as explained in the readme

### ISSUE THREAD

**Issue by alexanderadam** [ankane/dexter#27]
Other than [explained in the readme](https://github.com/ankane/dexter#connection-options) this won't use user `postgres`:

`dexter -U postgres -p 5432 -d database`

but this will:

`dexter postgresql://postgres@localhost:5432/database`

**Comment by ankane** [comment]
Hey @alexanderadam, thanks for reporting 👍 Fixed on master.

**Comment by alexanderadam** [comment]
Awesome, thank you for your blazingly fast response :+1:
