### ISSUE TITLE
Need 50% cost savings to suggest index

### ISSUE THREAD

**Issue by livingsilver94** [ankane/dexter#28]
Hello,
I have a pretty easy yet slow query I'm trying to speed up. Dexter doesn't find more indexes to help speeding it up and with `--log-sql --log-level debug2` it returns "Need 50% cost savings to suggest index". What's the meaning of this?

**Comment by ankane** [comment]
Hey @livingsilver94, that means it found an index, but the index didn't provide enough cost savings (based on EXPLAIN) to be recommended.

**Comment by livingsilver94** [comment]
Thanks a lot! Definitely helping :smile:
