### ISSUE TITLE
Add Docker configuration

### ISSUE THREAD

**Issue by sfkeller** [ankane/dexter#31]
Dockerize: 

Add Docker config, like here https://gitlab.com/geometalab/dexter-pg-bench-dockerized 

P.S. No updates on this nice project since years?

**Comment by ankane** [comment]
Hey @sfkeller, can you explain more? Dexter has a Dockerfile here: https://github.com/ankane/dexter/blob/master/Dockerfile

**Comment by ankane** [comment]
Closing due to no response
