### ISSUE TITLE
ERROR:  could not access file "$libdir/hypopg": No such file or directory

### ISSUE THREAD

**Issue by k2xl** [ankane/dexter#33]
Getting `ERROR:  could not access file "$libdir/hypopg": No such file or directory`
when running
```tail -F -n +1 log/postgresql.log | dexter --min-cost-savings-pct 30```

**Comment by ankane** [comment]
Hey @k2xl, this error means there's an issue with the HypoPG installation. Try reinstalling it.

**Comment by k2xl** [comment]
Solved it by reinstalling hypopg, then DROP EXTENSION hypopg and CREATE EXTENSION again
