### ISSUE TITLE
Not finding tables

### ISSUE THREAD

**Issue by k2xl** [ankane/dexter#34]
I'm trying with min-percent 0, with debugging and sql log turned on seeing this in dexter logs:

```No tables

SELECT CAST("public"."jhd_sooth"."Date" AS date) AS "Date", sum("public"."jhd_sooth"."New_Deaths") AS "sum", sum("public"."jhd_sooth"."ICU_Beds") AS "sum_2" FROM "public"."jhd_sooth" WHERE date_trunc('year', CAST("public"."jhd_sooth"."Date" AS timestamp)) = date_trunc('year', CAST(now() AS timestamp)) GROUP BY CAST("public"."jhd_sooth"."Date" AS date) ORDER BY CAST("public"."jhd_sooth"."Date" AS date) ASC
```

I'm wondering if the regex can't find the `jhd_sooth` table since it's in the form `"public"."jhd_sooth"`?

**Comment by ankane** [comment]
Hey @k2xl, can you paste the complete output for that query with `--log-sql --log-level debug2`? Dexter uses the Postgres parser to parse queries (thanks to pg_query) rather than regexes.

**Comment by ankane** [comment]
Closing due to no response
