### ISSUE TITLE
Build centos 7/8 rpm for version 0.3.8

### ISSUE THREAD

**Issue by gmekhrenin** [ankane/dexter#36]
Hi. 
In the repo now 
Name        : dexter
Arch        : x86_64
Version     : **0.3.5**
Release     : 1596005490.d58c6650.centos7
Size        : 102 M
Repo        : installed
From repo   : dexter
Summary     : The automatic indexer for Postgres
URL         : http://example.com/no-uri-given
License     : unknown
Description : The automatic indexer for Postgres

**Comment by ankane** [comment]
Thanks @gmekhrenin, looks like the previous build failed. Fixed now: https://packager.io/gh/pghero/dexter/
