### ISSUE TITLE
Installation instructions don't work for CentOS 8

### ISSUE THREAD

**Issue by denizdogan** [ankane/dexter#37]
```
--2020-10-27 09:37:08--  https://dl.packager.io/srv/pghero/dexter/master/installer/el/8.2.2004.repo
Resolving dl.packager.io (dl.packager.io)... 178.63.71.248
Connecting to dl.packager.io (dl.packager.io)|178.63.71.248|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2020-10-27 09:37:09 ERROR 400: Bad Request.
```

It seems that for some reason `lsb_release -rs` is returning 8.2.2004 when it should be 8. I installed `lsb_release` using `dnf -y install redhat-lsb-core`, if that should matter.

**Comment by denizdogan** [comment]
Same goes for Debian Stretch, it tries to download `https://dl.packager.io/srv/pghero/dexter/master/installer/debian/9.13.repo`

**Comment by ankane** [comment]
Hey @denizdogan, thanks for reporting! Can you try replacing `$(lsb_release -rs)` with `$(. /etc/os-release && echo $VERSION_ID)`? If that works, will update the instructions.

**Comment by denizdogan** [comment]
@ankane It seems to work for Debian! It's hard for me to try for CentOS now that I've switched my solution to be Debian-based. :)

**Comment by ankane** [comment]
Great, thanks for confirming. It worked in the CentOS Docker image, so think it's safe to update.
