### ISSUE TITLE
Not sure if its working

### ISSUE THREAD

**Issue by Rico1911** [ankane/dexter#40]
Hi,

i am new to this, and since i had great performance results on mssql databases by using indexes i wondered about postgre as well. Now i installed dexter and so far this is the Result:

`-bash-4.2$ dexter --log-sql --log-level debug3
[sql] SELECT * FROM pg_available_extensions WHERE name = 'hypopg' AND installed_version IS NOT NULL
[sql] SET lock_timeout = '5s'
Started
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
`

is this normal should this be the behavior?
When i try to parse Log files it wont work as follow error:

`-bash-4.2$ dexter -h localhost -p5432 -U postgres -p 5432 -d xxx /mnt/data/xxx/data/pg_log/postgresql-Wed.log
Started
ERROR: No such file or directory @ rb_sysopen - postgres
`
i hope thats nothing stupid to ask :) Version is latest 0.3.9

Thanks for help

**Comment by ankane** [comment]
Hey @Rico1911, for the first example, it looks like there isn't any input (no stdin or log file). For the 2nd one, try changing `-p5432` to `-p 5432`.
