### ISSUE TITLE
Bad Request when installing command line tool on Ubuntu

### ISSUE THREAD

**Issue by levinotik** [ankane/dexter#42]
I am following the instructions [here](https://github.com/ankane/dexter) and am getting a `400`. Any ideas on how to resolve that?

```bash
root@db:/tmp/hypopg-1.3.1# wget -O /etc/apt/sources.list.d/dexter.list https://dl.packager.io/srv/pghero/dexter/master/installer/ubuntu/$(. /etc/os-release && echo $VERSION_ID).repo
--2022-08-03 19:21:21--  https://dl.packager.io/srv/pghero/dexter/master/installer/ubuntu/9.repo
Resolving dl.packager.io (dl.packager.io)... 178.63.71.248
Connecting to dl.packager.io (dl.packager.io)|178.63.71.248|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2022-08-03 19:21:22 ERROR 400: Bad Request
```

**Comment by levinotik** [comment]
Actually, could I just install the command line tool outside of the DB server? In my case, I'm running PG in a Docker container. If I'm able to run the CL tool on the host machine (my Mac), I can just do that.

**Comment by ankane** [comment]
Hey @levinotik, for the 400 error, it looks like `$VERSION_ID` is `9` when it should be something like `20.04`. What does `cat /etc/os-release` show?

Also, the command line tool can be run on a separate machine from the database server, but the HypoPG extension needs to be installed on the database server (the `make` commands need to be run there).

**Comment by levinotik** [comment]
Thanks for the reply @ankane Looks like `9` correct though:

```bash
root@db:/tmp/hypopg-1.3.1# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by ankane** [comment]
It looks like you're on Debian, so you'll want to follow the Debian instructions.

For HypoPG, try using `psql` to connect to the DB server with same credentials you're passing to Dexter and running the following to verify that it's installed:

```sql
SELECT * FROM hypopg_list_indexes;
```

(should return 0 rows)

**Comment by levinotik** [comment]
@ankane hah I did realize that after I sent. Hadn't realized that HypoPG was available as a package using the PGDG packages, thanks a lot!

**Comment by levinotik** [comment]
`SELECT * FROM hypopg_list_indexes;` does return 0 rows now and everything _seems_ to be setup correctly. When tailing the logs, all I see is `Processing 0 new query fingerprints`.

```bash
Started
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
Processing 0 new query fingerprints
```

What am I doing wrong here? :)

**Comment by ankane** [comment]
Great, glad it's working!
