### ISSUE TITLE
Error while getting query stats

### ISSUE THREAD

**Issue by saifxd7** [ankane/dexter#47]
I ran command ` docker run -ti ankane/dexter postgres://postgres:secret@host.docker.internal:5433/permify --pg-stat-statements`

It gives this errors:
![image](https://github.com/ankane/dexter/assets/48759364/a290a3a0-b4f1-4103-a38d-bd2649508517)

please help me out @ankane !

**Comment by ankane** [comment]
Hi @saifxd7, it looks like you need to add `pg_stat_statements` to `shared_preload_libraries` in `postgresql.conf`.

https://github.com/ankane/pghero/blob/master/guides/Query-Stats.md
