### ISSUE TITLE
`--fail-when-found`

### ISSUE THREAD

**Issue by yegor256** [ankane/dexter#58]
First of all, many thanks for the great tool! We are trying to integrate it into our rake-powered build, but not only to help us find new indexes, but also to fail the build if such candidates exist. By doing this, we may guarantee that our web app will be released to production only when its DB schema is as fast as it can be (we use Liquibase).

Unfortunately, currently dexter doesn't fail when indexes are found. I suggest adding a new command line option `--fail-when-found` that will cause dexter to exit with a non-zero code if any index candidates are found.

**Comment by yegor256** [comment]
@ankane please, take a look

**Comment by ankane** [comment]
Hi @yegor256, thanks for the suggestion. However, I don't think it's common enough to add (but you could probably create a wrapper script to do this).

**Comment by yegor256** [comment]
@ankane respect your decision, but ask you to reconsider it. Currently, dexter can only be used as an interactive tool in hands of a programmer doing PostgreSQL optimization. With the introduced option the tool may be used as an element of a CI/CD pipeline.
