### ISSUE TITLE
Add option --include

### ISSUE THREAD

**Issue by stevelacy** [ankane/dexter#8]
We have a db with many tables, several that should be inspected individually.
Would you be willing to accept a PR to add an option flag `--include` to only include specific tables?

I added a commit to my fork, but am not sure if that is the best way to do the filter since I am not a ruby programmer. https://github.com/stevelacy/dexter/commit/d5cbad9f8dfd74aca60f14a6f0c0e92ed30b08f6

**Comment by ankane** [comment]
Hey @stevelacy, looks great 👍 Feel free to submit a PR.
